---
- name: Install/Update Software
  hosts: localhost

  vars:
    dockitems_remove:
      - Apps
      - "App Store"
      - Calendar
      - Contacts
      - FaceTime
      - Freeform
      - Games
      - iPhone Mirroring
      - Image Playground
      - Journal
      - Launchpad
      - Maps
      - Music
      - News
      - Notes
      - Phone
      - Photos
      - Passwords
      - Reminders
      - "Siri AI"
      - "System Settings"
      - TV
    dockitems_persist:
      - name: "Safari"
        path: "/Applications/Safari.app"
        pos: 1
      - name: "Brave Browser"
        path: "/Applications/Brave Browser.app"
        pos: 2
      - name: "Messages"
        path: "/System/Applications/Messages.app"
        pos: 3
      - name: "Mail"
        path: "/System/Applications/Mail.app"
        pos: 4
      - name: "Terminal"
        path: "/System/Applications/Utilities/Terminal.app"
        pos: 5
      - name: "ChatGPT"
        path: "/Applications/ChatGPT.app"
        pos: 6
      - name: "Cursor"
        path: "/Applications/Cursor.app"
        pos: 7
      - name: "Sublime Text"
        path: "/Applications/Sublime Text.app"
        pos: 8
      - name: "GitHub Desktop"
        path: "/Applications/GitHub Desktop.app"
        pos: 9
      - name: "Transmit"
        path: "/Applications/Transmit.app"
        pos: 10
      - name: "Windows App"
        path: "/Applications/Windows App.app"
        pos: 11
      - name: "Screen Sharing"
        path: "/System/Applications/Utilities/Screen Sharing.app"
        pos: 12

    homebrew_installed_packages:
      - btop
      - mas
      - wget
    homebrew_cask_apps:
      - brave-browser
      - chatgpt
      - cursor
      - discord
      - docker
      - github
      - font-victor-mono
      - keka
      - plex
      - sublime-text
      - transmit
      - vlc
      - winbox

    mas_installed_apps:
      - { id: 1543920362, name: "Displaperture" }
      - { id: 1295203466, name: "Windows App" }
    mas_uninstalled_apps: []

  pre_tasks:
    - name: dockutil utility
      become: false
      community.general.homebrew:
        name: dockutil
        state: present

    - name: Check for Oh My Zsh installation
      ansible.builtin.stat:
        path: ~/.oh-my-zsh
      register: oh_my_zsh_installed

    - name: Check if mas is signed in
      ansible.builtin.command: /opt/homebrew/bin/mas account
      register: mas_account_check
      changed_when: false
      failed_when: false
      become: false

    #- name: Fail if mas is not signed in
    #  ansible.builtin.fail:
    #    msg: |
    #      mas (Mac App Store CLI) is not signed in. Please sign in first by running:
    #      mas signin your-apple-id@example.com
    #
    #      Or if you want to sign in interactively:
    #      mas signin
    #  when: mas_account_check.rc != 0
    #  become: false

    - name: Get current username
      ansible.builtin.set_fact:
        current_user: "{{ ansible_facts['env']['USER'] | default(ansible_facts['user_id']) }}"

    - name: Configure passwordless sudo for mas
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/mas
        line: "{{ current_user }} ALL=(ALL) NOPASSWD: /opt/homebrew/bin/mas"
        create: yes
        validate: "visudo -cf %s"
        mode: "0440"
      become: true

  tasks:
    - name: Hush login
      ansible.builtin.shell: touch ~/.hushlogin

    - name: Oh My Zsh
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: ~/.oh-my-zsh
      environment:
        PATH: "{{ ansible_facts['env']['PATH'] }}"

    - name: MesloLGS NF Regular (font)
      ansible.builtin.get_url:
        url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
        dest: ~/Library/Fonts/MesloLGS NF Regular.ttf

    - name: MesloLGS NF Bold (font)
      ansible.builtin.get_url:
        url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
        dest: ~/Library/Fonts/MesloLGS NF Bold.ttf

    - name: MesloLGS NF Italic (font)
      ansible.builtin.get_url:
        url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
        dest: ~/Library/Fonts/MesloLGS NF Italic.ttf

    - name: MesloLGS NF Bold Italic (font)
      ansible.builtin.get_url:
        url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
        dest: ~/Library/Fonts/MesloLGS NF Bold Italic.ttf

    - name: Powerlevel10k theme
      ansible.builtin.git:
        repo: "https://github.com/romkatv/powerlevel10k.git"
        dest: "{{ ansible_facts['env']['HOME'] }}/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1

    - name: Set ZSH_THEME
      ansible.builtin.lineinfile:
        path: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
        regexp: "^ZSH_THEME="
        line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
        create: yes

    # - name: SoundSource
    #   ansible.builtin.shell: |
    #     curl -o ~/Downloads/SoundSource.zip https://cdn.rogueamoeba.com/soundsource/download/SoundSource.zip && \
    #     unzip -o ~/Downloads/SoundSource.zip -d /Applications/
    #     rm ~/Downloads/SoundSource.zip
    #   args:
    #     creates: /Applications/SoundSource.app
    #   environment:
    #     PATH: "{{ ansible_facts['env']['PATH'] }}"

    # - name: Audio Hijack
    #   ansible.builtin.shell: |
    #     curl -o ~/Downloads/AudioHijack.zip https://cdn.rogueamoeba.com/audiohijack/download/AudioHijack.zip && \
    #     unzip -o ~/Downloads/AudioHijack.zip -d /Applications/
    #     rm ~/Downloads/AudioHijack.zip
    #   args:
    #     creates: /Applications/Audio Hijack.app
    #   environment:
    #     PATH: "{{ ansible_facts['env']['PATH'] }}"

    # - name: Loopback
    #   ansible.builtin.shell: |
    #     curl -o ~/Downloads/Loopback.zip https://cdn.rogueamoeba.com/loopback/download/Loopback.zip && \
    #     unzip -o ~/Downloads/Loopback.zip -d /Applications/
    #     rm ~/Downloads/Loopback.zip
    #   args:
    #     creates: /Applications/Loopback.app
    #   environment:
    #     PATH: "{{ ansible_facts['env']['PATH'] }}"

    - name: Run OS Script
      ansible.builtin.shell: ./os.sh
      args:
        chdir: "{{ playbook_dir }}"

    - name: Clone zsh-autosuggestions repository
      git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions"
        dest: "{{ ansible_facts['env']['HOME'] }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        update: yes

    - name: Ensure zsh-autosuggestions is added to plugins list in .zshrc
      lineinfile:
        path: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
        regexp: '^plugins=\('
        line: "plugins=(git zsh-autosuggestions)"
        state: present
        backrefs: yes

    - name: Clone zsh-syntax-highlighting repository
      git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
        dest: "{{ ansible_facts['env']['HOME'] }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        update: yes

    - name: Ensure zsh-syntax-highlighting is added to plugins list in .zshrc
      lineinfile:
        path: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
        regexp: '^plugins=\('
        line: "plugins=(git zsh-autosuggestions zsh-syntax-highlighting)"
        state: present
        backrefs: yes

    - name: Ensure nvm configuration is added to .zshrc
      blockinfile:
        path: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
        block: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
          [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR NVM"
      become: yes

  roles:
    - name: geerlingguy.mac.homebrew
    - name: geerlingguy.mac.mas
    - name: geerlingguy.mac.dock
